<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Catalog\Block\Product\View */
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . $block->escapeHtmlAttr(__('* Required Fields')) . '"';
}
?>
<div class="product-options-wrapper" id="product-options-wrapper"<?= /* @noEscape */ $required ?>>
    <div class="fieldset" tabindex="0">
        <?= $block->getChildHtml('', true) ?>
    </div>
    <script type="text/javascript">
    require([
        'jquery'
        ], function ($) {
            $(window).load(function(){
                
                $('.upload-artwork').hide();
                
                $(document).on('change', '.design select', function(){
                    var select_type = $(this).children("option:selected").html();
                    console.log(select_type);
                    // if(select_type != '-- Please Select --' &&( select_type != 'I need design assistance +QAR 100.00' || select_type != 'I need design assistance +QAR 50.00')){
                        if(select_type== "I have a design" ){
                            
                    //    console.log("i am testing");
                        $('.upload-artwork').show();
                    } else {
                        console.log("i am test");
                        $('.upload-artwork').hide();
                    }
                    var str2 = '4 Color';
                    if(select_type.indexOf(str2) != -1){
                        $( ".quantity select option" ).each(function( index ) {
                            if($(this).html() != '2000'){
                                $(this).hide();
                            } else {
                                $(this).show();
                            }
                        });
                    } else {
                        $( ".quantity select option" ).show();
                    }
                });
                        
            }); 
        });
    </script>
    

</div>
