<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Text */ ?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
$id = strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $block->escapeHtml($_option->getTitle()))));
?>
<div class="field<?php if ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_AREA) {
    echo ' textarea';
                 } ?><?= /* @noEscape */ $class ?> <?= $id ?>">
    <label class="label" for="options_<?= $block->escapeHtmlAttr($_option->getId()) ?>_text">
        <?php if($id == 'select-sticker') { ?>
        <i class="fas fa-file-alt"></i>
        <?php } ?>
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
        <?= /* @noEscape */ $block->getFormattedPrice() ?>
    </label>

    <div class="control">
        <?php if ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_FIELD) :?>
            <?php $_textValidate = null;
            if ($_option->getIsRequire()) {
                $_textValidate['required'] = true;
            }
            if ($_option->getMaxCharacters()) {
                $_textValidate['maxlength'] = $_option->getMaxCharacters();
            }
            $_textValidate['validate-no-utf8mb4-characters'] = true;
            ?>
            <?php if($id == 'select-sticker') {
                $inputType = 'hidden';
            } else {
                $inputType = 'text';
            } ?>
            <input type="<?= $inputType ?>"
                   id="options_<?= $block->escapeHtmlAttr($_option->getId()) ?>_text"
                   class="input-text product-custom-option"
                <?php if (!empty($_textValidate)) {?>
                    data-validate="<?= $block->escapeHtmlAttr(json_encode($_textValidate)) ?>"
                <?php } ?>
                   name="options[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                   data-selector="options[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                   value="<?= $block->escapeHtmlAttr($block->getDefaultValue()) ?>"/>
                   
            <!-- Sticker Code -->
            <?php if($id == 'select-sticker') { ?>
            <div class="popupCode">
                <a class="action btn stickerButton" data-trigger="trigger">Stickers Gallery</a>
                <div data-bind="mageInit: {
                    'Magento_Ui/js/modal/modal':{
                        'type': 'popup',
                        'title': 'Select Image',
                        'trigger': '[data-trigger=trigger]',
                        'responsive': true,
                    }}">
                    <div class="content">
                        <?php
                        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
    	                if($block) {
    		                $block->setBlockId('stickerpopupcontent');
    		                echo '<div class="popup_images">'.$block->toHtml().'</div>';
    	                }
    	                ?>
                    </div>
                </div>
            </div>
            <div class="selected_stickers">
                <div class="selectedtext"><p>Your Choice:<br /><span class="selectedName"></span></p></div>
                <div class="selectedimg"></div>
            </div>
            <script type="text/javascript">
            require([
                'jquery'
                ], function ($) {
                    $(window).load(function(){
                        $(document).on('click', '.popup_images img', function(){
                           $('.popup_images img').removeClass('active');
                           $(this).addClass('active');
                           var title = $(this).attr('title');
                           var url = $(this).attr('src');
                           $('.selectedName').html(title);
                           $('.selectedimg').html('<div class="imgSelected"><img src="'+url+'"/><span class="remove"></span></div>');
                           $('.select-sticker input').val(title);
                        });
                        $(document).on('click', '.imgSelected .remove', function(){
                           $('.popup_images img').removeClass('active');
                           $('.selectedName').html('');
                           $('.selectedimg').html('');
                           $('.select-sticker input').val('');
                        });       
                    }); 
                });
            </script>
            
            <?php } ?>
                   
        <?php elseif ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_AREA) :?>
            <?php $_textAreaValidate = null;
            if ($_option->getIsRequire()) {
                $_textAreaValidate['required'] = true;
            }
            if ($_option->getMaxCharacters()) {
                $_textAreaValidate['maxlength'] = $_option->getMaxCharacters();
            }
            $_textAreaValidate['validate-no-utf8mb4-characters'] = true;
            ?>
            <textarea id="options_<?= $block->escapeHtmlAttr($_option->getId()) ?>_text"
                      class="product-custom-option"
                    <?php if (!empty($_textAreaValidate)) {?>
                        data-validate="<?= $block->escapeHtmlAttr(json_encode($_textAreaValidate)) ?>"
                    <?php } ?>
                      name="options[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                      data-selector="options[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                      rows="5"
                      cols="25"><?= $block->escapeHtml($block->getDefaultValue()) ?></textarea>
        <?php endif; ?>
        <?php if ($_option->getMaxCharacters()) :?>
            <p class="note note_<?= $block->escapeHtmlAttr($_option->getId()) ?>">
                <?= $block->escapeHtml(__('Maximum %1 characters', $_option->getMaxCharacters())) ?>
                <span class="character-counter no-display"></span>
            </p>
        <?php endif; ?>
    </div>
    <?php if ($_option->getMaxCharacters()) :?>
        <script type="text/x-magento-init">
        {
            "[data-selector='options[<?= $block->escapeJs($_option->getId()) ?>]']": {
                "Magento_Catalog/js/product/remaining-characters": {
                    "maxLength":  "<?= (int)$_option->getMaxCharacters() ?>",
                    "noteSelector": ".note_<?= $block->escapeJs($_option->getId()) ?>",
                    "counterSelector": ".note_<?= $block->escapeJs($_option->getId()) ?> .character-counter"
                }
            }
        }
    </script>
    <?php endif; ?>
</div>
