<?php

namespace MageArray\Formulaprice\Setup;

use Magento\Eav\Setup\EavSetupFactory;
use Magento\Framework\Setup\InstallDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;

class InstallData implements InstallDataInterface
{
    public function __construct(EavSetupFactory $eavSetupFactory)
    {
        $this->eavSetupFactory = $eavSetupFactory;
    }

    public function install(
        ModuleDataSetupInterface $setup,
        ModuleContextInterface $context
    ) {
        $eavSetup = $this->eavSetupFactory->create(['setup' => $setup]);
        $eavSetup
            ->addAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'formula_price_enable',
                [
                    'type' => 'int',
                    'label' => 'Enable Formula Price',
                    'input' => 'boolean',
                    'required' => false,
                    'frontend' => '',
                    'source' => '',
                    'backend' => '',
                    'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                    'user_defined' => true,
                    'searchable' => false,
                    'filterable' => false,
                    'visible_in_advanced_search' => false,
                    'used_in_product_listing' => false,
                    'is_filterable_in_grid' => false,
                    'is_filterable_in_search' => false,
                    'used_for_sort_by' => false,
                    'apply_to' => '',
                    'group' => 'Formula Price',
                    'sort_order' => 1,
                    'note' => "Activate module for this product",
                ]
            )->addAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'formula_price_final',
                [
                    'type' => 'varchar',
                    'label' => 'Final Equation for Price',
                    'input' => 'textarea',
                    'required' => false,
                    'frontend' => '',
                    'source' => '',
                    'backend' => '',
                    'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                    'user_defined' => true,
                    'searchable' => false,
                    'filterable' => false,
                    'visible_in_advanced_search' => false,
                    'used_in_product_listing' => false,
                    'is_filterable_in_grid' => false,
                    'is_filterable_in_search' => false,
                    'used_for_sort_by' => false,
                    'apply_to' => '',
                    'group' => 'Formula Price',
                    'sort_order' => 2,
                    'note' => "Example : {area}*{price}+{fixed_surcharge}+{extra}",
                ]
            )->addAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'formula_price_variable',
                [
                    'type' => 'text',
                    'label' => 'Assign Variable to Custom Option Title',
                    'input' => 'textarea',
                    'required' => false,
                    'frontend' => '',
                    'source' => '',
                    'backend' => '',
                    'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                    'user_defined' => true,
                    'searchable' => false,
                    'filterable' => false,
                    'visible_in_advanced_search' => false,
                    'used_in_product_listing' => false,
                    'is_filterable_in_grid' => false,
                    'is_filterable_in_search' => false,
                    'used_for_sort_by' => false,
                    'apply_to' => '',
                    'group' => 'Formula Price',
                    'sort_order' => 3,
                    'note' => "Example : Width=>wid;Length=>len",
                ]
            )->addAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'assign_custom_option_value',
                [
                    'type' => 'text',
                    'label' => 'Assign Variable to Custom Option Value',
                    'input' => 'textarea',
                    'required' => false,
                    'frontend' => '',
                    'source' => '',
                    'backend' => '',
                    'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                    'user_defined' => true,
                    'searchable' => false,
                    'filterable' => false,
                    'visible_in_advanced_search' => false,
                    'used_in_product_listing' => false,
                    'is_filterable_in_grid' => false,
                    'is_filterable_in_search' =>false,
                    'used_for_sort_by' => false,
                    'apply_to' => '',
                    'group' => 'Formula Price',
                    'sort_order' => 4,
                    'note' => "Example : {Red}=>10;{Black}=>5;{Blue}=>12;{White}=>12",
                ]
            )->addAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'formula_price_min',
                [
                    'type' => 'text',
                    'label' => 'Min Input Setting',
                    'input' => 'textarea',
                    'required' => false,
                    'frontend' => '',
                    'source' => '',
                    'backend' => '',
                    'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                    'user_defined' => true,
                    'searchable' => false,
                    'filterable' => false,
                    'visible_in_advanced_search' => false,
                    'used_in_product_listing' => false,
                    'is_filterable_in_grid' => false,
                    'is_filterable_in_search' => false,
                    'used_for_sort_by' => false,
                    'apply_to' => '',
                    'group' => 'Formula Price',
                    'sort_order' => 8,
                    'note' => "Example : wid=>12; len=>12",
                ]
            )->addAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'formula_price_min_var',
                [
                    'type' => 'text',
                    'label' => 'Min Input Validation Msg',
                    'input' => 'text',
                    'required' => false,
                    'frontend' => '',
                    'source' => '',
                    'backend' => '',
                    'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                    'user_defined' => true,
                    'searchable' => false,
                    'filterable' => false,
                    'visible_in_advanced_search' => false,
                    'used_in_product_listing' => false,
                    'is_filterable_in_grid' => false,
                    'is_filterable_in_search' => false,
                    'used_for_sort_by' => false,
                    'apply_to' => '',
                    'group' => 'Formula Price',
                    'sort_order' => 9,
                    'note' => "Example : Minimum {title} is {min} -> Minimum Width is 12",
                ]
            )->addAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'formula_price_max',
                [
                    'type' => 'text',
                    'label' => 'Max Input Setting',
                    'input' => 'textarea',
                    'required' => false,
                    'frontend' => '',
                    'source' => '',
                    'backend' => '',
                    'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                    'user_defined' => true,
                    'searchable' => false,
                    'filterable' => false,
                    'visible_in_advanced_search' => false,
                    'used_in_product_listing' => false,
                    'is_filterable_in_grid' => false,
                    'is_filterable_in_search' => false,
                    'used_for_sort_by' => false,
                    'apply_to' => '',
                    'group' => 'Formula Price',
                    'sort_order' => 10,
                    'note' => "Example : wid=>22; len=>22",
                ]
            )->addAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'formula_price_max_var',
                [
                    'type' => 'text',
                    'label' => 'Max Input Validation Msg',
                    'input' => 'text',
                    'required' => false,
                    'frontend' => '',
                    'source' => '',
                    'backend' => '',
                    'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                    'user_defined' => true,
                    'searchable' => false,
                    'filterable' => false,
                    'visible_in_advanced_search' => false,
                    'used_in_product_listing' => false,
                    'is_filterable_in_grid' => false,
                    'is_filterable_in_search' => false,
                    'used_for_sort_by' => false,
                    'apply_to' => '',
                    'group' => 'Formula Price',
                    'sort_order' => 11,
                    'note' => "Example : Maximum {title} is {max} -> Minimum Width is 22",
                ]
            )->addAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'static_fixed_variable',
                [
                    'type' => 'text',
                    'label' => 'Static Variables For Equation',
                    'input' => 'textarea',
                    'required' => false,
                    'frontend' => '',
                    'source' => '',
                    'backend' => '',
                    'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                    'user_defined' => true,
                    'searchable' => false,
                    'filterable' => false,
                    'visible_in_advanced_search' => false,
                    'used_in_product_listing' => false,
                    'is_filterable_in_grid' => false,
                    'is_filterable_in_search' => false,
                    'used_for_sort_by' => false,
                    'apply_to' => '',
                    'group' => 'Formula Price',
                    'sort_order' => 5,
                    'note' => "Example : fixed_surcharge=>10;extra=>2",
                ]
            )->addAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'static_variable_equation',
                [
                    'type' => 'text',
                    'label' => 'Static Variables ( Formula Based ) For Equation',
                    'input' => 'textarea',
                    'required' => false,
                    'frontend' => '',
                    'source' => '',
                    'backend' => '',
                    'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                    'user_defined' => true,
                    'searchable' => false,
                    'filterable' => false,
                    'visible_in_advanced_search' => false,
                    'used_in_product_listing' => false,
                    'is_filterable_in_grid' => false,
                    'is_filterable_in_search' => false,
                    'used_for_sort_by' => false,
                    'apply_to' => '',
                    'group' => 'Formula Price',
                    'sort_order' => 6,
                    'note' => "Example : area=>{wid}*{len}",
                ]
            )->addAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'extra_price_formula',
                [
                    'type' => 'text',
                    'label' => 'Extra Price Formula ( Discount / Upcharge )',
                    'input' => 'textarea',
                    'required' => false,
                    'frontend' => '',
                    'source' => '',
                    'backend' => '',
                    'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                    'user_defined' => true,
                    'searchable' => false,
                    'filterable' => false,
                    'visible_in_advanced_search' => false,
                    'used_in_product_listing' => false,
                    'is_filterable_in_grid' => false,
                    'is_filterable_in_search' => false,
                    'used_for_sort_by' => false,
                    'apply_to' => '',
                    'group' => 'Formula Price',
                    'sort_order' => 7,
                    'note' => "Example : ({wid}>=10 && {len}<=10)=>-({newprice}*0.5/100)+{extra}",
                ]
            );
    }
}
